spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true

server.port=8080
server.error.include-message=always
server.error.include-stacktrace=always

logging.level.root=INFO
logging.level.com.mipt.todolist=DEBUG
logging.level.org.springframework.web=DEBUG

management.endpoints.web.exposure.include=beans,health,info,env
