spring:
  application:
    name: "MIPT-TaskManager-API"
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: false

app:
  version: "1.0.0-SNAPSHOT"
  description: "MVP Task Manager for MIPT Spring Course"
  tasks:
    default-status: "PENDING"

spring.jackson:
  serialization:
    indent_output: true
    write_dates_as_timestamps: false