spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true

server.port=80
server.server-header=Task-Manager-Server
server.error.include-stacktrace=never
server.error.include-message=never

logging.level.root=WARN
logging.level.com.mipt.todolist=INFO
logging.file.name=logs/task-manager-prod.log
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB

management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
